[pyprland]
plugins = [
    "scratchpads"
]

[pyprland.variables]
term = "foot"

[scratchpads.term]
command = "[term] --app-id=scratchpad-term fish"
class = "scratchpad-term"
size = "60% 60%"
position = "20% 20%"
preserve_aspect = true

[scratchpads.ncmpcpp]
command = "[term] --app-id=scratchpad=ncmpcpp ncmpcpp"
class = "scratchpad-ncmpcpp"
size = "80% 80%"
position = "10% 10%"
